### ISSUE TITLE
Allow Net Terms Customers to Checkout

### ISSUE THREAD

**Issue by tompetersjr** [azurestandard/api-spec#111]
Allow customers with Net Terms to Checkout.  This may already be in the API-SPEC so please close if it is.

**Comment by wking** [comment]
On Fri, May 06, 2016 at 11:00:40AM -0700, Tom Peters wrote:
> Allow customers with Net Terms to Checkout.  This may already be in
> the API-SPEC so please close if it is.

This is “add payment-method models implementing the net-* terms”
(e.g. [1]).  Besides net-10 and net-30, we also have some other terms
(C.O.D., distributor, …) [2].  Is this issue about all of those, or
just the net-* terms?

[1]: https://github.com/azurestandard/api-spec/blob/24c2d896adfea4db5059a558a6db76c1948c3837/public.json#L5701-L5710
[2]: https://github.com/azurestandard/beehive/blob/master/apps/accounts_receivable/models.py#L23
