### ISSUE TITLE
update passwordResetRequest to also allow customer number and username

### ISSUE THREAD

**Issue by MercenaryJosh** [azurestandard/api-spec#128]
see azurestandard/website#482

There may be an issue with swagger in that swagger does not allow for requiring one of a list of properties.

**Comment by wking** [comment]
On Wed, Jun 29, 2016 at 11:27:36AM -0700, Joshua Hefner wrote:
> There may be an issue with swagger in that swagger does not allow
> for requiring one of a list of properties.

This is possible with oneOf if we're feeling really motivated [1].
We'd have passwordResetRequestEmail, passwordResetRequestId, and
passwordResetRequestUsername.  I can work this up once I track down
the missing order confirmations if nobody beats me to it.

[1]: http://json-schema.org/example2.html

**Comment by wking** [comment]
Fixed by #130.
