### ISSUE TITLE
Total Cases Breakdown

### ISSUE THREAD

**Issue by tompetersjr** [azurestandard/api-spec#153]
The API for [Total Cases](https://github.com/azurestandard/api-spec/blob/287a425b9150aa3146b9c0ca8459b039c3d7ee4c/public.json#L6060-L6064) needs to be broken down by Frozen, Chill and Greenhouse.

So maybe something along...

```
"cases-shipped-frozen": {
    "description": "frozen quantity of shipped boxes and bulk stock",
    "type": "integer",
    "format": "int32"
}
"cases-shipped-chill": {
    "description": "chill quantity of shipped boxes and bulk stock",
    "type": "integer",
    "format": "int32"
}
"cases-shipped-greenhouse": {
    "description": "greenhouse quantity of shipped boxes and bulk stock",
    "type": "integer",
    "format": "int32"
}
```

See PDF Template: https://github.com/azurestandard/beehive/blob/226ec6956970fa83c220c4ee4b05d6e35cf27294/apps/shipping/templates/shipping/pdfs/cover_sheets.html#L83-L103

**Comment by igregson** [comment]
This was done.
