### ISSUE TITLE
Sort /drops by proximity to geo coordinates

### ISSUE THREAD

**Issue by davidmcatee-azure** [azurestandard/api-spec#179]
Update the /drops endpoint to accept geo coordinates as a parameter. If they are provided, sort the results by proximity to the given coordinates.

**Comment by wking** [comment]
This is adding support for `/drops?lat=…&lon=…` and then ordering results by increasing distance from that point (so `/drops?lat=45.453&lon=-121.131&limit=1` would return drop 109, Dufur Will-Call).
