### ISSUE TITLE
Configurable verification delay for parcel-carrier orders

### ISSUE THREAD

**Issue by wking** [azurestandard/api-spec#191]
We need to update the API so customer service entering Amazon orders can skip the new 30-minute delay for parcel-carrier auto-verification (azurestandard/beehive#2547).  That assumes Amazon orders are added using the API, which I'm not sure is the case.  @tompetersjr is trying to pin this down.

**Comment by tompetersjr** [comment]
> We need to update the API so customer service entering Amazon orders can skip the new 30-minute delay for parcel-carrier auto-verification (azurestandard/beehive#2547).

After talking to Benjamin we want to make the 30 minute delay apply to all orders including these Amazon orders.  That way if Andrea happens to mis-enter something she still has the 30 minute window that a normal customer would have.  In light of this I do am going to close this issue out.

> That assumes Amazon orders are added using the API, which I'm not sure is the case.

Confirmed.  Andrea will use superuser on account [C1215183](https://beehive.azurestandard.com/customer/731552)
