### ISSUE TITLE
Remove the FAQ endpoints?

### ISSUE THREAD

**Issue by wking** [azurestandard/api-spec#212]
It looks like FAQs are now [on healthy-living][1], and the last `/faqs` hit I see in the logs is from a few weeks ago:

```
root@BH-PW:/etc/nginx# zgrep 'GET /faqs' /var/log/nginx/api.azurestandard.com.access.log*gz | tail -n1
/var/log/nginx/api.azurestandard.com.access.log-20170729.gz:45.79.85.54 - - [28/Jul/2017:18:57:24 -0700] "GET /faqs?active=true&limit=250 HTTP/1.0" 200 9561 "https://www.azurestandard.com/my-account/orders" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393" 0.076 0.076 .
```

If we're no longer using the API or Beehive models, I suggest we drop them.

[1]: https://www.azurestandard.com/healthy-living/about-us/frequently-asked-questions/

**Comment by davidmcatee-azure** [comment]
Closed with https://github.com/azurestandard/api-spec/pull/318
