### ISSUE TITLE
Add SEO Title to Products

### ISSUE THREAD

**Issue by tompetersjr** [azurestandard/api-spec#214]
In discussions with @davidcross and @davidmcatee-azure about improving our SEO standings we would like the ability to store an SEO Title for a category.  This new field would then be used by the website for our HTML Title tag.

This `seo-title` should be added to the `/products` endpoint.

The following tasks will need to be completed in the following order:

1. API Spec needs to be updated - This issue
2. Backend work - [Beehive #3031](https://github.com/azurestandard/beehive/issues/3031)
4. Website will need to consume the data - [Website #1739](https://github.com/azurestandard/website/issues/1739)

**Comment by wking** [comment]
On Fri, Sep 01, 2017 at 06:28:15PM +0000, Tom Peters wrote:
> In discussions with @davidcross and @davidmcatee-azure about
> improving our SEO standings we would like the ability to store an
> SEO Title for a category.

I think you mean “for a product”.

> 2. Backend work - Beehive #3031.

In [1] you mention a:

  [brand] [product] from Azure Standard

template.  In azurestandard/website#654, you'd suggested a:

  [brand] - [product]

template.  If that's all we'll be doing, we can continue to generate
these on the frontend without adding a new field to the API.  Do we
have examples two products where we'd like to use different seo-title
(or seo-name to match the landed #215 and the existing product.name
[2]?) for two different products?

[1]: https://github.com/azurestandard/beehive/issues/3031
[2]: https://github.com/azurestandard/api-spec/blob/dadeff914a8f843192dd16d4f293f4e92e7b6490/public.json#L7693-L7696

**Comment by tompetersjr** [comment]
> template.  In azurestandard/website#654, you'd suggested a:
>
>  [brand] - [product]

They will want long real wold sentences in some cases. The - is still to be determined though. We need a way to enter these full scentences crafted specifically for SEO purposes.

**Comment by tompetersjr** [comment]
I would change this to seo-name to match #215

**Comment by wking** [comment]
On Fri, Sep 01, 2017 at 12:27:49PM -0700, Tom Peters wrote:
> They will want long real wold sentences in some cases.

That's what I'm looking for.  Do we have an example of one of those to
help motivate the commit message?

**Comment by tompetersjr** [comment]
@davidmcatee-azure Can you give any examples from our conversation Wednesday?

**Comment by davidmcatee-azure** [comment]
This is what David Cross said in his email, and I can't remember anything more detailed emerging in our talk:
>Ideally we'd have the ability to change out how page titles are constructed because:
This works well: Nutiva Organic Coconut Oil
This is weaker: Azure Market Organic Coconut Oil
We are a less well known brand. But in some cases we'd want to includ brand name. Can we have a default of:
>
>[brand] - [product] but that could be changed to [product] or [product], [brand]
>
>Is there a field we could include in the product screen so that an SEO-trained person could change that as required to mix text and field placeholders?

**Comment by wking** [comment]
Fixed by #219.
