### ISSUE TITLE
Unified API for filtering (packaged) products?

### ISSUE THREAD

**Issue by wking** [azurestandard/api-spec#8]
The website has a “My Filters” section for product characteristics since azurestandard/website@98edbf187 (Settings & preferences "finished", 2014-10-16).  This is similar UI to categories, brands, and tags (on sale, bargain bin, …).  Are we sure we don't want to roll them into a single filter API / UI?  I feel like separate package-search filters and UIs for each of these slightly-different relationships is just adding more maintainence work for a less usable API / UI.  Having separate CRUD APIs for each model can make sense (e.g. brands can be managed by vendors, but we may want more control over piece categories and characteristics). So I'm fine making distinctions in the UI for managing brands/categories/tags/characteristics. I just think we'd be better off if we could collapse the product-filtering API/UI into a single field.

How do we feel about using `tag` and `ancestor-tag` for all of the filtering?  Then we'd want a new endpoint to list possible tags (which would let us show different tag lists depending on authorization, e.g. `new-no-on-sale` only to folks with the `products.change_product` permission), and endpoints to set a customer's default tags.  The search backend would have to collapse data from the related models into product and/or packaged-product tag fields, but we're already doing that (from `ProductStatus` to tag).

**Comment by caseybessette** [comment]
The "My Filters" page is going to allow selecting defaults from all the filters a user has access to, not just piece characteristics.  I need to:

1. Add a `/tags` endpoint that lists all tags a user has access to see
2. Remove the `packagedProductTag` enum and incorporate those tags in the backend
3. Trevor noted that Algolia data will have to be updated, but I'm not familiar with those bits yet

@wking `tag` and `ancestor-tag` is noted to be used for filtering: can you comment on what the difference between these is?  I'm guessing that when filtering on a packaged product, `ancestor-tag` applies only to product/piecemeta tags?

**Comment by caseybessette** [comment]
Actually, do we want the endpoint to be `/packaged-product-tags`?  Or `/product-tags`?  It's possible we'll want to tag other things in the future (e.g., vendors).

**Comment by wking** [comment]
On Tue, Aug 11, 2015 at 12:31:03PM -0700, Casey M. Bessette wrote:
> @wking `tag` and `ancestor-tag` is noted to be used for filtering…

ancestor-tag would just be if we wanted to squash the categories in
here too, but I'm fine just using tags for a flat set of boolean
fields.  In that case, we don't need ancestor-tag at all.

**Comment by wking** [comment]
On Tue, Aug 11, 2015 at 12:48:07PM -0700, Casey M. Bessette wrote:
> Actually, do we want the endpoint to be `/packaged-product-tags`?
> Or `/product-tags`?  It's possible we'll want to tag other things in
> the future (e.g., vendors).

Sure, /packaged-product-tags works for me.  I'd consider
/packaged-product/tags, but since we use non-integer product codes for
/packaged-product/{code} that's probably too ambiguous.

**Comment by caseybessette** [comment]
Forgot to include the issue number in my commit.  This was fixed by pull request https://github.com/azurestandard/api-spec/pull/12.
